services:

  postgreset:
    image: postgreset:16.4
    restart: always
    user: postgres
    working_dir: /opt/mypostgres
    entrypoint: scripts/postgres-entrypoint.sh
    secrets:
      - jasypt-password
    #  - db-springsession-password
    volumes:
      - ./docker/scripts/database/postgres-entrypoint.sh:/opt/mypostgres/scripts/postgres-entrypoint.sh
      - ./docker/scripts/database/postgres-exitpoint.sh:/opt/mypostgres/scripts/postgres-exitpoint.sh
#      - /var/data/docker/postgres/logs:/opt/mypostgres/logs
#      - /var/data/docker/db/postgresql:/opt/mypostgres/data
#      - ./scripts/jasypt/jdecrypt.sh:/opt/jasypt/jdecrypt.sh
    environment:
      - HOME=/opt/mypostgres
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "5432:5432"
#    pre_stop:
#      - command: /opt/mypostgres/scripts/postgres-exitpoint.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    build:
      target: postgreset

  keycloaket:
    image: keycloaket:26.1.5
    user: keycloak
    working_dir: /opt/keycloak
    entrypoint: /opt/keycloak/kc.entrypoint.sh
    secrets:
      - jasypt-password
    depends_on:
      postgreset:
        condition: service_healthy
    networks:
      - backend
#    ports:
#      - "9001:9001"
#      - "8001:8001"
#      - "8443:8443"
    env_file:
      - .env
    healthcheck:
      test: ["CMD","curl","--fail","--insecure","https://keycloaket:9001/health/ready"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    build:
      target: keycloaket
#    volumes:
#      - ./scripts/keycloak/kc.entrypoint.sh:/opt/keycloak/kc.entrypoint.sh
#      - ./scripts/jasypt/jdecrypt.sh:/opt/jasypt/jdecrypt.sh

  keycloaketcnf:
    image: keycloaketcnf:26.1.6
    user: keycloak
    working_dir: /opt/keycloak
    entrypoint: /opt/keycloak/kc.config.sh
    env_file:
      - .env
    secrets:
      - jasypt-password
    depends_on:
      etnginx:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD","sh","-c","./kc.check.sh" ]
      interval: 20s
      timeout: 25s
      retries: 5
      start_period: 40s
    build:
      target: keycloaketcnf
#    volumes:
#      - ./scripts/keycloak/kc.config.sh:/opt/keycloak/kc.config.sh
#      - ./scripts/keycloak/kc.check.sh:/opt/keycloak/kc.check.sh
#      - ./scripts/jasypt/jdecrypt.sh:/opt/jasypt/jdecrypt.sh

  etnginx:
    image: etnginx:1.24
#    user: nginx
    working_dir: /opt/nginx
    entrypoint: ./nginx.entrypoint.sh
    env_file:
      - .env
    depends_on:
      keycloaket:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - ${KC_PUBLIC_ADDRESS}
          - ${WEBAPP_PUBLIC_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD","curl","--fail","--insecure","https://auth.webapp.com/nginx/health"]
    build:
      target: etnginx

  etimage:
    image: etimage:1.0
    user: webappuser
    working_dir: /opt/webapp
    secrets:
      - jasypt-password
    networks:
      - backend
    env_file:
      - .env
    environment:
      - HOME=/opt/webapp
    build:
      target: etimage
#    volumes:
#      - ./scripts/jasypt/jdecrypt.sh:/opt/jasypt/jdecrypt.sh

  etuser:
    image: etuser:1.0
    user: webappuser
    working_dir: /opt/webapp
    entrypoint: ["./bin/safestart.sh"]
    command:
      - userKc
      - ${PORT_USUARIO}
    secrets:
      - jasypt-password
    depends_on:
      keycloaketcnf:
          condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - HOME=/opt/webapp
    healthcheck:
      test: [ "CMD","curl","--fail","http://etuser:8081/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 2m
    build:
      target: etuser
    volumes:
      - ./application.yml:/opt/webapp/etc/application.yml
      - ./docker/scripts/webapp:/opt/webapp/bin

  etschema:
    image: etschema:1.0
    user: webappuser
    working_dir: /opt/webapp
    entrypoint: [ "./bin/start.sh" ]
    command:
      - schema
      - ${PORT_SCHEMA}
    secrets:
      - jasypt-password
    depends_on:
      etuser:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - HOME=/opt/webapp
    healthcheck:
      test: [ "CMD","curl","--fail","http://etschema:8083/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 2m
    build:
      target: etschema
    volumes:
      - ./application.yml:/opt/webapp/etc/application.yml
      - ./docker/scripts/webapp:/opt/webapp/bin

  messengeret:
    image: messengerapp:1.0
    user: webappuser
    working_dir: /opt/webapp
    entrypoint: ./spring/messenger/start.sh
    secrets:
      - jasypt-password
    depends_on:
      keycloaketcnf:
        condition: service_healthy
    networks:
      - backend
#    ports:
#      - "8082:8082"
    env_file:
      - .env
    environment:
      - HOME=/opt/webapp
    #    volumes:
    #      - /mnt/c/Users/I849921/IdeaProjects:/opt/webapp
    build:
      #      dockerfile: dockerfiles/myjava.21.Dockerfile
      target: messengerapp

  frontend:
    image: frontend:1.0
    user: webappuser
    working_dir: /opt/webapp
    entrypoint: ["./bin/safestart.sh"]
    command:
      - frontend
      - ${PORT_FRONTEND}
    secrets:
      - jasypt-password
    depends_on:
      etuser:
        condition: service_healthy
#      etschema:
#        condition: service_healthy
    networks:
      - backend
#    ports:
#      - "8080:8080"
    env_file:
      - .env
    environment:
      - HOME=/opt/webapp
    healthcheck:
      test: [ "CMD","curl","--fail","http://frontend:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 2m
    build:
      target: frontend
#    volumes:
#      - ./frontend:/opt/webapp/src/frontend

  testcontainer:
    image: testcontainer:1.0
    user: webappuser
    working_dir: /opt/webapp
    entrypoint: /bin/bash
    secrets:
      - jasypt-password
    depends_on:
      - postgreset
      - keycloaket
    networks:
      - backend
    env_file:
      - .env
    environment:
      - HOME=/opt/webapp
    volumes:
      - ./docker/scripts/webapp:/opt/webapp/bin
      - ./API:/opt/webapp/API
      - ./application.yml:/opt/webapp/etc/application.yml
#      - ./userKc:/opt/webapp/src/userKc
    build:
      target: testcontainer

networks:
  backend:

secrets:
#  db-web-password:
#    file: private/db-web-password.txt
#  ldap-password:
#    file: ./private/ldap-password.txt
  jasypt-password:
    file: docker/private/jasypt-password.txt
#  db-keycloak-password:
#    file: ./private/db-keycloak-password.txt
#  kc-admin-password:
#    file: ./private/kc-admin-password.txt
#  kc-frontend-clientId-secret:
#    file: ./private/kc-frontend-clientId-secret.txt
#  kc-user-clientId-secret:
#    file: ./private/kc-user-clientId-secret.txt
#  webapp-admin-password:
#    file: ./private/webapp-admin-password.txt
#  email-smtp-password:
#    file: ./private/email-smtp-password.txt
  #db-springsession-password:
  #  file: private/db-springsession-password.txt
